export const CREATE_RESIDENCE = 'CREATE_RESIDENCE';
export const EDIT_RESIDENCE = 'EDIT_RESIDENCE';
export const DELETE_RESIDENCE = 'DELETE_RESIDENCE';
export const FETCH_RESIDENCES = 'FETCH_RESIDENCES';
export const FETCH_RESIDENCE = 'FETCH_RESIDENCE';
